apiVersion: v1
kind: Pod
metadata:
  name: nfs-testing
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:v0.11
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
    volumeMounts:
    - name: nfs-volume
      mountPath: /nfs-test
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: cns-nfs-pvc