@startuml kubeconfig


cloud cluster {
    collections "k8s" as k8s
    file config as k8s_config
}


package "External Systems" {
    actor client as c
    file config as client_config
}

c -- client_config
k8s_config .. client_config
c --> k8s
