apiVersion: v1
baseDomain: ocp.com 
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: test 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
additionalTrustBundle: |
  
imageContentSources:
- mirrors:
    - {{ openshift_release_image_repository }}
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
    - {{ openshift_operator_image_repository }}
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
pullSecret: '{{ pull_secret }}'
sshKey: {{ ssh_key }}